# Generated by Django 5.0.6 on 2024-05-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cod'), ('CARD', 'Card')], default='COD', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
